/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package nq;

import nq.solver.BacktrackingSolver;
import nq.solver.GradientHeuristicSolver;
import nq.solver.utils.SolverUtils;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        int boardSize = 8;
        if (args.length > 0) {
            boardSize = Integer.parseInt(args[0]);
        }

        if (boardSize < 8) {
            System.out.println("Board size < 8 do not have valid solutions.");
            return;
        }

        // var solver = new BacktrackingSolver(boardSize, true);
        var solver = new GradientHeuristicSolver(boardSize, true);
        SolverUtils.printChessboard(solver.solve(), boardSize);
    }
}
